name: publish

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      - run: pip install -r requirements.txt
      - run: cd mkdocs && mkdocs gh-deploy --force